import { promises as fs } from 'node:fs'
import path from 'node:path'
import type { ApplyResult, DependencyEdit, Installer, InstallPlan } from './shared.js'

const GO_DEPS = [
  { name: 'go.opentelemetry.io/otel', version: 'v1.38.0' },
  { name: 'go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp', version: 'v1.38.0' },
  { name: 'go.opentelemetry.io/otel/sdk', version: 'v1.38.0' },
] as const

async function exists(file: string): Promise<boolean> {
  return fs.stat(file).then(() => true, () => false)
}

async function findMain(serviceDir: string): Promise<string | null> {
  const root = path.join(serviceDir, 'main.go')
  if (await exists(root)) return root
  const cmd = path.join(serviceDir, 'cmd')
  const entries = await fs.readdir(cmd, { withFileTypes: true }).catch(() => [])
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (!entry.isDirectory()) continue
    const candidate = path.join(cmd, entry.name, 'main.go')
    if (await exists(candidate)) return candidate
  }
  return null
}

export function neatOtelGo(packageName = 'main'): string {
  return `// neat-otel-init v1 — generated by NEAT. Safe to re-generate; do not edit.
package ${packageName}

import (
  "context"
  "os"
  "path/filepath"
  "runtime"
  "strings"

  "go.opentelemetry.io/otel"
  "go.opentelemetry.io/otel/attribute"
  "go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"
  sdktrace "go.opentelemetry.io/otel/sdk/trace"
  "go.opentelemetry.io/otel/trace"
)

type neatCallSiteSpanProcessor struct { root string }

func (p neatCallSiteSpanProcessor) OnStart(_ context.Context, span sdktrace.ReadWriteSpan) {
  if span.SpanKind() != trace.SpanKindClient && span.SpanKind() != trace.SpanKindProducer { return }
  pcs := make([]uintptr, 32)
  n := runtime.Callers(2, pcs)
  frames := runtime.CallersFrames(pcs[:n])
  for {
    frame, more := frames.Next()
    clean := filepath.Clean(frame.File)
    slash := filepath.ToSlash(clean)
    if clean != "" && strings.HasPrefix(clean, p.root+string(os.PathSeparator)) && !strings.Contains(slash, "/vendor/") && !strings.HasSuffix(slash, "/neat_otel.go") {
      span.SetAttributes(
        attribute.String("code.file.path", clean),
        attribute.Int("code.line.number", frame.Line),
        attribute.String("code.function.name", frame.Function),
      )
      return
    }
    if !more { return }
  }
}
func (neatCallSiteSpanProcessor) OnEnd(sdktrace.ReadOnlySpan) {}
func (neatCallSiteSpanProcessor) Shutdown(context.Context) error { return nil }
func (neatCallSiteSpanProcessor) ForceFlush(context.Context) error { return nil }

func init() {
  root := os.Getenv("NEAT_SERVICE_ROOT")
  if root == "" {
    _, self, _, ok := runtime.Caller(0)
    if !ok { return }
    root = filepath.Dir(self)
    for {
      if _, err := os.Stat(filepath.Join(root, "go.mod")); err == nil { break }
      parent := filepath.Dir(root)
      if parent == root { return }
      root = parent
    }
  }
  root, _ = filepath.Abs(root)
  if canonical, err := filepath.EvalSymlinks(root); err == nil { root = canonical }
  exporter, err := otlptracehttp.New(context.Background())
  if err != nil { return }
  provider := sdktrace.NewTracerProvider(
    sdktrace.WithBatcher(exporter),
    sdktrace.WithSpanProcessor(neatCallSiteSpanProcessor{root: filepath.Clean(root)}),
  )
  otel.SetTracerProvider(provider)
}
`
}

async function detect(serviceDir: string): Promise<boolean> {
  return exists(path.join(serviceDir, 'go.mod'))
}

async function plan(serviceDir: string): Promise<InstallPlan> {
  const manifest = path.join(serviceDir, 'go.mod')
  const raw = await fs.readFile(manifest, 'utf8')
  const main = await findMain(serviceDir)
  const dependencyEdits: DependencyEdit[] = GO_DEPS
    .filter((dep) => !raw.includes(dep.name))
    .map((dep) => ({ file: manifest, kind: 'add', ...dep }))
  if (!main) return { language: 'go', serviceDir, dependencyEdits: [], entrypointEdits: [], envEdits: [], libOnly: true }
  const source = await fs.readFile(main, 'utf8')
  const packageName = source.match(/^\s*package\s+(\w+)\s*$/m)?.[1] ?? 'main'
  const generated = path.join(path.dirname(main), 'neat_otel.go')
  const generatedFiles = (await exists(generated)) ? [] : [{ file: generated, contents: neatOtelGo(packageName) }]
  return { language: 'go', serviceDir, dependencyEdits, entrypointEdits: [], envEdits: [], generatedFiles, entryFile: main }
}

async function apply(installPlan: InstallPlan): Promise<ApplyResult> {
  if (installPlan.libOnly) return { serviceDir: installPlan.serviceDir, outcome: 'lib-only', writtenFiles: [] }
  const writtenFiles: string[] = []
  const byManifest = new Map<string, DependencyEdit[]>()
  for (const edit of installPlan.dependencyEdits) byManifest.set(edit.file, [...(byManifest.get(edit.file) ?? []), edit])
  for (const [manifest, edits] of byManifest) {
    const raw = await fs.readFile(manifest, 'utf8')
    const suffix = raw.endsWith('\n') ? '' : '\n'
    await fs.writeFile(manifest, `${raw}${suffix}${edits.map((e) => `require ${e.name} ${e.version}`).join('\n')}\n`, 'utf8')
    writtenFiles.push(manifest)
  }
  for (const generated of installPlan.generatedFiles ?? []) {
    if (await exists(generated.file)) continue
    await fs.writeFile(generated.file, generated.contents, 'utf8')
    writtenFiles.push(generated.file)
  }
  return { serviceDir: installPlan.serviceDir, outcome: writtenFiles.length ? 'instrumented' : 'already-instrumented', writtenFiles }
}

export const goInstaller: Installer = { name: 'go', detect, plan, apply }
