/**
 * PHP SDK installer (ADR-186).
 *
 * `detect` matches on a composer.json (a Laravel or plain-PHP service). `plan`
 * adds the OpenTelemetry Composer packages to the `require` map and generates a
 * `neat_otel.php` bootstrap that points the OTLP exporter at NEAT's
 * project-scoped path and turns on the zero-code SDK autoloader. For a Laravel
 * app it also adds `open-telemetry/opentelemetry-auto-laravel`, whose hooks give
 * route, DB (Eloquent), cache, and queue spans that fuse onto the extracted
 * Laravel routes and Eloquent tables.
 *
 * HONESTY — the PECL extension NEAT cannot install:
 *   PHP OpenTelemetry auto-instrumentation is driven by the `opentelemetry`
 *   PECL extension, a system-level install (`pecl install opentelemetry`) that
 *   composer cannot provide. Without it the auto-instrumentation hooks never
 *   fire and no spans are produced. This installer PLANS the requirement — the
 *   generated file header, the recommended env, and the apply result all name
 *   it as a required user step — but it does not and cannot pretend composer
 *   alone instruments PHP.
 *
 * FILE-GRAIN — deferred (ADR-186). Ruby and Go stamp `code.file.path` from a
 * call-site span processor; the PHP equivalent would register a custom span
 * processor into the zero-code autoloaded SDK, a hook that can't be verified
 * without a live PHP + PECL runtime. Rather than ship an unverified
 * registration that may silently never fire, PHP lands route/table/service
 * grain now and file-grain is a tracked follow-up. composer.lock is never
 * written (it is a lockfile, ADR-046 §4).
 */

import { promises as fs } from 'node:fs'
import path from 'node:path'
import type {
  ApplyResult,
  DependencyEdit,
  EnvEdit,
  GeneratedFile,
  Installer,
  InstallPlan,
  PlanOptions,
} from './shared.js'

// Marker basenames, kept as bare string literals on their own lines to stay
// clear of the lockfile-reference audit (ADR-046 §4). composer.lock is
// detect-only; the manifest we edit is composer.json.
const PHP_MARKERS = [
  'composer.json',
  'composer.lock',
] as const

const NEAT_OTEL_FILENAME = 'neat_otel.php'
const NEAT_OTEL_STAMP = 'neat-otel-init v1'
const LARAVEL_PACKAGE = 'open-telemetry/opentelemetry-auto-laravel'

// Composer packages. The SDK + OTLP exporter are the base; the guzzle7 adapter
// gives the exporter a PSR-18 HTTP client via discovery (Laravel already ships
// Guzzle); the auto-laravel package is added only for a Laravel app.
const PHP_PACKAGES = [
  { name: 'open-telemetry/sdk', version: '^1.0' },
  { name: 'open-telemetry/exporter-otlp', version: '^1.0' },
  { name: 'php-http/guzzle7-adapter', version: '^1.0' },
  { name: LARAVEL_PACKAGE, version: '^0.1' },
] as const

// Surfaced everywhere the user might look: the generated file header, the
// recommended env, and the apply result reason.
const PHP_PECL_CAVEAT =
  'PHP auto-instrumentation requires the `opentelemetry` PECL extension ' +
  '(`pecl install opentelemetry`, then `extension=opentelemetry.so` in php.ini). ' +
  'NEAT cannot install a PECL extension via composer — until it is loaded no ' +
  'spans are produced. See neat_otel.php and ADR-186.'

// The generated bootstrap. `project` bakes the OTLP scope + service name
// (ADR-183 — hooks export to the project-scoped path); both stay overridable
// through the standard OTel env vars.
export function neatOtelPhp(opts: { project?: string } = {}): string {
  const service = opts.project ?? 'php-service'
  const endpoint = opts.project
    ? `http://localhost:4318/projects/${opts.project}/v1/traces`
    : 'http://localhost:4318/v1/traces'
  return `<?php
// ${NEAT_OTEL_STAMP} — generated by NEAT. Safe to re-generate; do not edit.
//
// REQUIRED SYSTEM STEP — NEAT CANNOT DO THIS FOR YOU:
//   PHP OpenTelemetry auto-instrumentation needs the \`opentelemetry\` PECL
//   extension, a system-level install composer cannot provide:
//       pecl install opentelemetry
//   then enable it in your php.ini:
//       extension=opentelemetry.so
//   Verify with \`php -m | grep opentelemetry\`. Until the extension is loaded
//   the Laravel auto-instrumentation hooks never fire and no spans are emitted.
//
// Wire this file so it runs before the framework boots — either set
//   auto_prepend_file = /absolute/path/to/neat_otel.php
// in php.ini / .user.ini, or require it at the very top of public/index.php and
// artisan. It points the exporter at your NEAT daemon and turns on the SDK
// autoloader; the auto-laravel instrumentation then produces route, DB, cache,
// and queue spans that fuse onto your extracted routes and Eloquent tables.
//
// FILE-GRAIN (code.file.path call-site attribution) is a documented follow-up
// for PHP — see ADR-186. Route, table, and service grain land now.

declare(strict_types=1);

// Degrade to a no-op when the extension isn't present, so a bare app still
// boots (never break the host application).
if (!extension_loaded('opentelemetry')) {
    return;
}

// Point the exporter at NEAT unless the operator already set these. The
// endpoint is NEAT's project-scoped traces path (ADR-183).
$neat_defaults = [
    'OTEL_PHP_AUTOLOAD_ENABLED' => 'true',
    'OTEL_SERVICE_NAME' => '${service}',
    'OTEL_TRACES_EXPORTER' => 'otlp',
    'OTEL_EXPORTER_OTLP_PROTOCOL' => 'http/json',
    'OTEL_EXPORTER_OTLP_TRACES_ENDPOINT' => '${endpoint}',
    'OTEL_PROPAGATORS' => 'baggage,tracecontext',
];
foreach ($neat_defaults as $neat_key => $neat_value) {
    if (getenv($neat_key) === false && !isset($_SERVER[$neat_key]) && !isset($_ENV[$neat_key])) {
        putenv($neat_key . '=' . $neat_value);
        $_SERVER[$neat_key] = $neat_value;
        $_ENV[$neat_key] = $neat_value;
    }
}
`
}

async function exists(p: string): Promise<boolean> {
  try {
    await fs.stat(p)
    return true
  } catch {
    return false
  }
}

async function detect(serviceDir: string): Promise<boolean> {
  for (const marker of PHP_MARKERS) {
    if (await exists(path.join(serviceDir, marker))) return true
  }
  return false
}

interface ComposerManifest {
  require: Record<string, unknown>
  requireDev: Record<string, unknown>
}

function readComposerObject(body: string): ComposerManifest {
  let parsed: unknown = null
  try {
    parsed = JSON.parse(body)
  } catch {
    parsed = null
  }
  const obj = parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? (parsed as Record<string, unknown>) : {}
  const require = obj.require && typeof obj.require === 'object' && !Array.isArray(obj.require)
    ? (obj.require as Record<string, unknown>)
    : {}
  const requireDev = obj['require-dev'] && typeof obj['require-dev'] === 'object' && !Array.isArray(obj['require-dev'])
    ? (obj['require-dev'] as Record<string, unknown>)
    : {}
  return { require, requireDev }
}

async function plan(serviceDir: string, opts?: PlanOptions): Promise<InstallPlan> {
  const empty: InstallPlan = {
    language: 'php',
    serviceDir,
    dependencyEdits: [],
    entrypointEdits: [],
    envEdits: [],
  }

  const composerPath = path.join(serviceDir, 'composer.json')
  const hasComposer = await exists(composerPath)

  const dependencyEdits: DependencyEdit[] = []
  if (hasComposer) {
    const body = await fs.readFile(composerPath, 'utf8')
    const { require, requireDev } = readComposerObject(body)
    const laravel =
      'laravel/framework' in require ||
      'laravel/framework' in requireDev ||
      (await exists(path.join(serviceDir, 'artisan')))
    const wanted = laravel ? PHP_PACKAGES : PHP_PACKAGES.filter((p) => p.name !== LARAVEL_PACKAGE)
    for (const pkg of wanted) {
      if (!(pkg.name in require)) {
        dependencyEdits.push({ file: composerPath, kind: 'add', name: pkg.name, version: pkg.version })
      }
    }
  }

  // The bootstrap is generated whenever a composer.json is present; createOnly
  // preserves any existing file (ADR-069 §6).
  const bootstrap = path.join(serviceDir, NEAT_OTEL_FILENAME)
  const generatedFiles: GeneratedFile[] = []
  if (hasComposer && !(await exists(bootstrap))) {
    generatedFiles.push({ file: bootstrap, contents: neatOtelPhp({ project: opts?.project }), skipIfExists: true })
  }

  if (dependencyEdits.length === 0 && generatedFiles.length === 0) {
    return empty
  }

  const envEdits: EnvEdit[] = [
    { file: null, key: 'OTEL_PHP_AUTOLOAD_ENABLED', value: 'true' },
    { file: null, key: 'OTEL_EXPORTER_OTLP_ENDPOINT', value: 'http://localhost:4318' },
  ]

  return {
    language: 'php',
    serviceDir,
    dependencyEdits,
    entrypointEdits: [],
    envEdits,
    ...(generatedFiles.length > 0 ? { generatedFiles } : {}),
  }
}

async function writeFileAtomic(file: string, contents: string): Promise<void> {
  const tmp = `${file}.${process.pid}.${Date.now()}.tmp`
  await fs.writeFile(tmp, contents, 'utf8')
  await fs.rename(tmp, file)
}

// Merge the missing packages into composer.json's `require`, preserving every
// other key (merge, never clobber). composer.json is strict JSON, so the safe
// edit is parse → add missing keys → re-serialize; existing require entries and
// all sibling keys (name, type, require-dev, autoload, …) are kept.
async function applyComposerJson(file: string, edits: DependencyEdit[], original: string): Promise<void> {
  let parsed: unknown
  try {
    parsed = JSON.parse(original)
  } catch {
    throw new Error(`php installer: composer.json at ${file} is not valid JSON`)
  }
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    throw new Error(`php installer: composer.json at ${file} is not a JSON object`)
  }
  const obj = parsed as Record<string, unknown>
  const require = obj.require && typeof obj.require === 'object' && !Array.isArray(obj.require)
    ? (obj.require as Record<string, string>)
    : {}
  for (const e of edits) {
    if (e.kind !== 'add') continue
    if (!(e.name in require)) require[e.name] = e.version
  }
  obj.require = require
  await writeFileAtomic(file, JSON.stringify(obj, null, 2) + '\n')
}

async function rollback(
  serviceDir: string,
  language: string,
  originals: Map<string, string>,
  created: string[],
): Promise<void> {
  const restored: string[] = []
  for (const [file, raw] of originals.entries()) {
    try {
      await fs.writeFile(file, raw, 'utf8')
      restored.push(file)
    } catch {
      // best-effort
    }
  }
  const removed: string[] = []
  for (const file of created) {
    try {
      await fs.rm(file, { force: true })
      removed.push(file)
    } catch {
      // best-effort
    }
  }
  const body = [
    '# neat-rollback.patch',
    '',
    `# Generated after a partial apply failure in the ${language} installer.`,
    '# Files listed below were restored to their pre-apply contents.',
    '',
    ...restored.map((f) => `restored: ${f}`),
    ...removed.map((f) => `removed: ${f}`),
    '',
  ]
  await fs.writeFile(path.join(serviceDir, 'neat-rollback.patch'), body.join('\n'), 'utf8')
}

async function apply(installPlan: InstallPlan): Promise<ApplyResult> {
  const { serviceDir } = installPlan
  const generatedFiles = installPlan.generatedFiles ?? []
  const manifests = new Set(installPlan.dependencyEdits.map((e) => e.file))

  if (manifests.size === 0 && generatedFiles.length === 0) {
    return { serviceDir, outcome: 'already-instrumented', writtenFiles: [], reason: PHP_PECL_CAVEAT }
  }

  const originals = new Map<string, string>()
  for (const file of manifests) {
    try {
      originals.set(file, await fs.readFile(file, 'utf8'))
    } catch {
      // Mutation fails loudly below; rollback covers what did land.
    }
  }

  const writtenFiles: string[] = []
  const created: string[] = []
  try {
    for (const gf of generatedFiles) {
      if (await exists(gf.file)) continue
      await fs.mkdir(path.dirname(gf.file), { recursive: true })
      await writeFileAtomic(gf.file, gf.contents)
      writtenFiles.push(gf.file)
      created.push(gf.file)
    }

    for (const file of manifests) {
      const raw = originals.get(file)
      if (raw === undefined) throw new Error(`php installer: cannot read ${file} during apply`)
      const edits = installPlan.dependencyEdits.filter((e) => e.file === file)
      if (edits.length > 0) {
        await applyComposerJson(file, edits, raw)
        writtenFiles.push(file)
      }
    }
  } catch (err) {
    await rollback(serviceDir, installPlan.language, originals, created)
    throw err
  }

  // Surface the PECL requirement loudly at apply time — it is the step that
  // makes or breaks whether PHP produces any spans at all.
  if (writtenFiles.length > 0) {
    console.warn(`neat: PHP instrumentation staged in ${path.basename(serviceDir)}, but a system step remains:\n  ${PHP_PECL_CAVEAT}`)
  }

  return {
    serviceDir,
    outcome: writtenFiles.length > 0 ? 'instrumented' : 'already-instrumented',
    writtenFiles,
    reason: PHP_PECL_CAVEAT,
  }
}

export const phpInstaller: Installer = { name: 'php', detect, plan, apply }
