/**
 * Python SDK installer (ADR-047).
 *
 * `detect` matches on the canonical Python project markers — requirements.txt,
 * pyproject.toml, setup.py. `plan` produces dependency edits against the
 * primary manifest and entrypoint edits against a Procfile when one exists.
 *
 * MVP scope:
 *  - requirements.txt is the full-fidelity manifest (read / append).
 *  - pyproject.toml dependencies live inside a TOML `dependencies = [...]`
 *    block; we line-insert into that block when found, otherwise hold off
 *    on rewriting until a successor ADR addresses TOML editing properly.
 *  - Procfile lines starting with `python` get prefixed with
 *    `opentelemetry-instrument`.
 *
 * Lockfiles (poetry.lock, Pipfile.lock) are never touched. After `--apply`,
 * init's summary tells the user to run `pip install -r requirements.txt`
 * (or `poetry lock && poetry install`) so they own the lockfile commit.
 */

import { promises as fs } from 'node:fs'
import path from 'node:path'
import type {
  ApplyResult,
  DependencyEdit,
  EntrypointEdit,
  EnvEdit,
  GeneratedFile,
  Installer,
  InstallPlan,
} from './shared.js'

const SDK_PACKAGES = [
  { name: 'opentelemetry-distro', version: '>=0.49b0' },
  { name: 'opentelemetry-exporter-otlp', version: '>=1.28.0' },
] as const

const OTEL_ENV: EnvEdit = {
  file: null,
  key: 'OTEL_EXPORTER_OTLP_ENDPOINT',
  value: 'http://localhost:4318',
}

const NEAT_OTEL_FILENAME = 'neat_otel.py'
const NEAT_OTEL_STAMP = 'neat-otel-init v1'
const NEAT_IMPORT_LINE = 'import neat_otel  # neat: call-site file attribution'

// The generated Python call-site span processor (ADR-151, file-awareness.md §4)
// — Python's analog of the Node processor in installers/templates.ts. It stamps
// the stable OpenTelemetry code attributes (`code.file.path` / `code.line.number`
// / `code.function.name`, semconv ≥1.33 — the names ingest reads, ADR-152) on
// CLIENT/PRODUCER/SERVER spans by walking the stack to the first application
// frame, so NEAT fuses a runtime span onto the source file that issued it.
// Verified against a live FastAPI + SQLAlchemy app: DB and HTTP-client spans
// resolve to the caller's file:line even across an `await`; a SERVER span is
// created before the handler runs, so it stays route/service-grained, honestly.
// Registration is import-time — under `opentelemetry-instrument` the SDK provider
// is configured before the app module imports, so `add_span_processor` lands on
// the real provider. If OpenTelemetry is absent the module degrades to a no-op
// rather than breaking the host app (the ADR-144 discipline).
export function neatOtelPy(): string {
  return `# ${NEAT_OTEL_STAMP} — generated by NEAT. Safe to re-generate; do not edit.
# Call-site file attribution (docs/contracts/file-awareness.md section 4). Stamps
# code.file.path / code.line.number / code.function.name on spans so NEAT fuses
# runtime spans onto your source files. Import it once at your entry point.
import os
import sys

try:
    from opentelemetry import trace as _neat_trace
    from opentelemetry.sdk.trace import SpanProcessor as _NeatSpanProcessor
    from opentelemetry.trace import SpanKind as _NeatSpanKind

    _NEAT_OTEL = True
except Exception:
    _NEAT_OTEL = False

if _NEAT_OTEL:
    _NEAT_SELF = os.path.abspath(__file__)
    _NEAT_PREFIXES = tuple(
        os.path.abspath(p) + os.sep
        for p in {sys.prefix, sys.base_prefix, sys.exec_prefix, sys.base_exec_prefix}
    )
    _NEAT_KINDS = {_NeatSpanKind.CLIENT, _NeatSpanKind.PRODUCER, _NeatSpanKind.SERVER}

    def _neat_is_user_frame(filename):
        if not filename:
            return False
        if filename.startswith("<") and filename.endswith(">"):
            return False
        abs_name = os.path.abspath(filename)
        if abs_name == _NEAT_SELF:
            return False
        parts = abs_name.split(os.sep)
        if "opentelemetry" in parts or "site-packages" in parts:
            return False
        for pref in _NEAT_PREFIXES:
            if abs_name.startswith(pref):
                return False
        return True

    class NeatCallSiteSpanProcessor(_NeatSpanProcessor):
        def on_start(self, span, parent_context=None):
            try:
                if span.kind not in _NEAT_KINDS:
                    return
                frame = sys._getframe(1)
                while frame is not None:
                    if _neat_is_user_frame(frame.f_code.co_filename):
                        span.set_attribute("code.file.path", os.path.abspath(frame.f_code.co_filename))
                        span.set_attribute("code.line.number", frame.f_lineno)
                        span.set_attribute("code.function.name", frame.f_code.co_name)
                        return
                    frame = frame.f_back
            except Exception:
                pass  # never break the host application

        def on_end(self, span):
            pass

        def shutdown(self):
            pass

        def force_flush(self, timeout_millis=30000):
            return True

    def _neat_register():
        try:
            provider = _neat_trace.get_tracer_provider()
            add = getattr(provider, "add_span_processor", None)
            if callable(add):
                add(NeatCallSiteSpanProcessor())
        except Exception:
            pass

    if os.environ.get("NEAT_CALLSITE_DISABLED", "") != "1":
        _neat_register()
`
}

async function writeFileAtomic(file: string, contents: string): Promise<void> {
  const tmp = `${file}.${process.pid}.${Date.now()}.tmp`
  await fs.writeFile(tmp, contents, 'utf8')
  await fs.rename(tmp, file)
}

// Resolve the Python entry-point file to inject the neat_otel import into. Reads
// the Procfile run command (`uvicorn app:app`, `gunicorn app:app`, `python
// main.py`, `fastapi run app.py`) and resolves the module to a file; falls back
// to the conventional entry-point names.
async function resolvePyEntrypoint(serviceDir: string): Promise<string | null> {
  const procfile = path.join(serviceDir, 'Procfile')
  if (await exists(procfile)) {
    const raw = await fs.readFile(procfile, 'utf8')
    for (const line of raw.split(/\r?\n/)) {
      const m = line.match(/^[a-zA-Z0-9_-]+:\s*(.+)$/)
      if (!m) continue
      const cmd = m[1]!
      const asgi = cmd.match(/\b(?:uvicorn|gunicorn|hypercorn|daphne)\s+([\w.]+):/)
      if (asgi) {
        const modPath = asgi[1]!.replace(/\./g, '/')
        const asFile = path.join(serviceDir, `${modPath}.py`)
        if (await exists(asFile)) return asFile
        const asPkg = path.join(serviceDir, modPath, '__init__.py')
        if (await exists(asPkg)) return asPkg
      }
      const runFile = cmd.match(/\b(?:python3?|fastapi\s+(?:run|dev))\s+([\w./-]+\.py)\b/)
      if (runFile) {
        const p = path.join(serviceDir, runFile[1]!)
        if (await exists(p)) return p
      }
    }
  }
  for (const name of ['main.py', 'app.py', 'asgi.py', 'wsgi.py', 'manage.py', 'server.py']) {
    const p = path.join(serviceDir, name)
    if (await exists(p)) return p
  }
  return null
}

// Insert `import neat_otel` at the top of an entry-point's source, after a
// shebang and any `from __future__` imports (which must stay first, or Python
// raises a SyntaxError). Idempotent: returns null when the import is already
// present. A leading module docstring is demoted, which is harmless.
export function injectNeatImport(source: string): string | null {
  if (/^\s*import\s+neat_otel\b/m.test(source)) return null
  const lines = source.split('\n')
  let insertAt = lines[0]?.startsWith('#!') ? 1 : 0
  for (let i = 0; i < Math.min(lines.length, 15); i++) {
    if (/^\s*from\s+__future__\s+import\b/.test(lines[i] ?? '')) insertAt = i + 1
  }
  lines.splice(insertAt, 0, NEAT_IMPORT_LINE)
  return lines.join('\n')
}

async function exists(p: string): Promise<boolean> {
  try {
    await fs.stat(p)
    return true
  } catch {
    return false
  }
}

async function detect(serviceDir: string): Promise<boolean> {
  const markers = ['requirements.txt', 'pyproject.toml', 'setup.py']
  for (const m of markers) {
    if (await exists(path.join(serviceDir, m))) return true
  }
  return false
}

// Strip a requirements.txt line down to its lower-cased package name.
// `flask==3.0.0` → `flask`, `Flask>=2 ; python_version>"3.6"` → `flask`.
function reqPackageName(line: string): string {
  const stripped = line.split('#')[0]?.trim() ?? ''
  const head = stripped.split(/[\s;]/)[0] ?? ''
  return head.replace(/[<>=!~].*$/, '').toLowerCase()
}

async function planRequirementsTxtEdits(
  serviceDir: string,
): Promise<{ manifest: string; missing: typeof SDK_PACKAGES[number][] } | null> {
  const file = path.join(serviceDir, 'requirements.txt')
  if (!(await exists(file))) return null
  const raw = await fs.readFile(file, 'utf8')
  const presentNames = new Set(
    raw
      .split(/\r?\n/)
      .map(reqPackageName)
      .filter((n) => n.length > 0),
  )
  const missing = SDK_PACKAGES.filter((p) => !presentNames.has(p.name.toLowerCase()))
  return { manifest: file, missing: [...missing] }
}

async function planProcfileEdits(serviceDir: string): Promise<EntrypointEdit[]> {
  const procfile = path.join(serviceDir, 'Procfile')
  if (!(await exists(procfile))) return []
  const raw = await fs.readFile(procfile, 'utf8')
  const edits: EntrypointEdit[] = []
  for (const line of raw.split(/\r?\n/)) {
    if (line.length === 0) continue
    // Procfile lines look like `<process>: <cmd>`. Prefix the cmd when it
    // starts with python and isn't already wrapped.
    const m = line.match(/^([a-zA-Z0-9_-]+):\s*(.+)$/)
    if (!m) continue
    const cmd = m[2]!
    if (!/^python\b/.test(cmd)) continue
    if (cmd.startsWith('opentelemetry-instrument ')) continue
    const after = `${m[1]}: opentelemetry-instrument ${cmd}`
    edits.push({ file: procfile, before: line, after })
  }
  return edits
}

async function plan(serviceDir: string): Promise<InstallPlan> {
  const empty: InstallPlan = {
    language: 'python',
    serviceDir,
    dependencyEdits: [],
    entrypointEdits: [],
    envEdits: [],
  }

  const dependencyEdits: DependencyEdit[] = []
  const reqs = await planRequirementsTxtEdits(serviceDir)
  if (reqs) {
    for (const sdk of reqs.missing) {
      dependencyEdits.push({
        file: reqs.manifest,
        kind: 'add',
        name: sdk.name,
        version: sdk.version,
      })
    }
  }
  // pyproject.toml / setup.py without requirements.txt: deferred to a
  // successor ADR. The patch will note it; apply is a no-op for those
  // manifests in the MVP.

  const entrypointEdits = await planProcfileEdits(serviceDir)

  // The call-site processor gives Python file-grain OBSERVED (ADR-151): a
  // generated neat_otel.py plus an `import neat_otel` at the resolved entry
  // point. Only planned when an entry point resolves — a processor module the
  // app never imports would be dead weight, not instrumentation.
  const entryFile = await resolvePyEntrypoint(serviceDir)
  const generatedFiles: GeneratedFile[] = entryFile
    ? [{ file: path.join(serviceDir, NEAT_OTEL_FILENAME), contents: neatOtelPy() }]
    : []

  if (dependencyEdits.length === 0 && entrypointEdits.length === 0 && !entryFile) {
    return empty
  }
  return {
    language: 'python',
    serviceDir,
    dependencyEdits,
    entrypointEdits,
    envEdits: [OTEL_ENV],
    ...(generatedFiles.length > 0 ? { generatedFiles } : {}),
    ...(entryFile ? { entryFile } : {}),
  }
}

async function applyRequirementsTxt(
  manifest: string,
  edits: DependencyEdit[],
  original: string,
): Promise<void> {
  // Append missing packages on their own lines. Preserve a trailing newline.
  const newlines = edits
    .filter((e) => e.kind === 'add')
    .map((e) => `${e.name}${e.version}`)
  const trailing = original.endsWith('\n') ? '' : '\n'
  const next = `${original}${trailing}${newlines.join('\n')}\n`
  const tmp = `${manifest}.${process.pid}.${Date.now()}.tmp`
  await fs.writeFile(tmp, next, 'utf8')
  await fs.rename(tmp, manifest)
}

async function applyProcfile(
  procfile: string,
  edits: EntrypointEdit[],
  original: string,
): Promise<void> {
  let next = original
  for (const e of edits) {
    if (!next.includes(e.before)) continue
    next = next.replace(e.before, e.after)
  }
  const tmp = `${procfile}.${process.pid}.${Date.now()}.tmp`
  await fs.writeFile(tmp, next, 'utf8')
  await fs.rename(tmp, procfile)
}

async function apply(installPlan: InstallPlan): Promise<ApplyResult> {
  const { serviceDir, entryFile } = installPlan
  const generatedFiles = installPlan.generatedFiles ?? []
  const touched = new Set<string>()
  for (const e of installPlan.dependencyEdits) touched.add(e.file)
  for (const e of installPlan.entrypointEdits) touched.add(e.file)
  if (entryFile) touched.add(entryFile)
  if (touched.size === 0 && generatedFiles.length === 0) {
    return { serviceDir, outcome: 'already-instrumented', writtenFiles: [] }
  }

  const originals = new Map<string, string>()
  for (const file of touched) {
    try {
      originals.set(file, await fs.readFile(file, 'utf8'))
    } catch {
      // Mutation will fail loudly below; rollback covers what did land.
    }
  }

  const writtenFiles: string[] = []
  const createdFiles: string[] = []
  try {
    // Generated files first (neat_otel.py). Idempotent: an identical file is
    // left untouched; a new one is tracked so rollback can delete it.
    for (const gf of generatedFiles) {
      const already = await exists(gf.file)
      if (already) {
        const cur = await fs.readFile(gf.file, 'utf8').catch(() => null)
        if (cur === gf.contents) continue
      }
      await writeFileAtomic(gf.file, gf.contents)
      writtenFiles.push(gf.file)
      if (!already) createdFiles.push(gf.file)
    }

    for (const file of touched) {
      const raw = originals.get(file)
      if (raw === undefined) {
        throw new Error(`python installer: cannot read ${file} during apply`)
      }
      const base = path.basename(file)
      if (base === 'requirements.txt') {
        const edits = installPlan.dependencyEdits.filter((e) => e.file === file)
        if (edits.length > 0) {
          await applyRequirementsTxt(file, edits, raw)
          writtenFiles.push(file)
        }
      } else if (base === 'Procfile') {
        const edits = installPlan.entrypointEdits.filter((e) => e.file === file)
        if (edits.length > 0) {
          await applyProcfile(file, edits, raw)
          writtenFiles.push(file)
        }
      } else if (file === entryFile) {
        // Inject `import neat_otel` so the call-site processor registers at
        // startup. Idempotent — a re-run leaves an already-injected entry alone.
        const injected = injectNeatImport(raw)
        if (injected !== null) {
          await writeFileAtomic(file, injected)
          writtenFiles.push(file)
        }
      }
      // pyproject.toml / setup.py: MVP no-op as planned above.
    }
  } catch (err) {
    await rollback(installPlan, originals, createdFiles)
    throw err
  }

  const outcome = writtenFiles.length > 0 ? 'instrumented' : 'already-instrumented'
  return { serviceDir, outcome, writtenFiles }
}

async function rollback(
  installPlan: InstallPlan,
  originals: Map<string, string>,
  createdFiles: string[] = [],
): Promise<void> {
  const restored: string[] = []
  for (const [file, raw] of originals.entries()) {
    try {
      await fs.writeFile(file, raw, 'utf8')
      restored.push(file)
    } catch {
      // Best-effort.
    }
  }
  const removed: string[] = []
  for (const file of createdFiles) {
    try {
      await fs.rm(file, { force: true })
      removed.push(file)
    } catch {
      // Best-effort.
    }
  }
  const lines = [
    '# neat-rollback.patch',
    '',
    `# Generated after a partial apply failure in the ${installPlan.language} installer.`,
    '# Files listed below were restored to their pre-apply contents.',
    '',
    ...restored.map((f) => `restored: ${f}`),
    ...removed.map((f) => `removed: ${f}`),
    '',
  ]
  const rollbackPath = path.join(installPlan.serviceDir, 'neat-rollback.patch')
  await fs.writeFile(rollbackPath, lines.join('\n'), 'utf8')
}

export const pythonInstaller: Installer = {
  name: 'python',
  detect,
  plan,
  apply,
}
