/**
 * Ruby SDK installer (ADR-186).
 *
 * `detect` matches on a Gemfile (a Rails or plain-Ruby service). `plan` adds
 * the OpenTelemetry gems to the Gemfile and — for a Rails app — generates a
 * `config/initializers/neat_otel.rb` that Rails auto-loads at boot. The
 * initializer configures the OTLP exporter at NEAT's project-scoped path,
 * enables the Ruby auto-instrumentation set (`use_all`), and installs a
 * call-site span processor that stamps the stable `code.*` attributes on
 * CLIENT/PRODUCER spans so a runtime span fuses onto the source file that
 * issued it (docs/contracts/file-awareness.md).
 *
 * The initializer is convention-loaded — Rails requires everything under
 * `config/initializers/` at startup — so there is no entry-point injection to
 * do, the same shape the Go installer's same-package `init()` and the Nuxt
 * `server/plugins/` convention take. Bundler's `Gemfile.lock` is never written
 * (it is a lockfile, ADR-046 §4); after `--apply` the user runs
 * `bundle install` so bundler resolves the lockfile itself.
 */

import { promises as fs } from 'node:fs'
import path from 'node:path'
import type {
  ApplyResult,
  DependencyEdit,
  EnvEdit,
  GeneratedFile,
  Installer,
  InstallPlan,
  PlanOptions,
} from './shared.js'

// Marker basenames. Kept as bare string literals on their own lines so the
// lockfile-reference audit (contracts.test.ts, ADR-046 §4) reads the only
// 'Gemfile.lock' occurrence as a set entry, never a write target — the manifest
// we edit is the Gemfile, the lock is detect-only.
const RUBY_MARKERS = [
  'Gemfile',
  'Gemfile.lock',
] as const

// Gems added to the Gemfile. The SDK + OTLP exporter mirror Python's
// distro/exporter pair; `opentelemetry-instrumentation-all` is the meta-gem
// that pulls Rails, ActiveRecord, Net::HTTP, PG, and the rest of the
// auto-instrumentation set, so a Rails app gets route + DB spans without
// naming each instrumentation gem individually.
const RUBY_GEMS = [
  { name: 'opentelemetry-sdk', version: '~> 1.5' },
  { name: 'opentelemetry-exporter-otlp', version: '~> 0.29' },
  { name: 'opentelemetry-instrumentation-all', version: '~> 0.62' },
] as const

const NEAT_OTEL_STAMP = 'neat-otel-init v1'
const INITIALIZER_REL = path.join('config', 'initializers', 'neat_otel.rb')

// The generated Rails initializer. `project` bakes the OTLP scope + service
// name (ADR-183 — hooks export to the project-scoped path, not the bare one);
// both stay overridable through the standard OTel env vars so an operator can
// point the app at a different daemon without regenerating the file.
export function neatOtelRb(opts: { project?: string } = {}): string {
  const service = opts.project ?? 'ruby-service'
  const endpoint = opts.project
    ? `http://localhost:4318/projects/${opts.project}/v1/traces`
    : 'http://localhost:4318/v1/traces'
  return `# ${NEAT_OTEL_STAMP} — generated by NEAT. Safe to re-generate; do not edit.
# Rails auto-loads this at boot (config/initializers/*). It points the
# OpenTelemetry SDK at your NEAT daemon, enables the Ruby auto-instrumentation
# set, and installs a span processor that stamps code.file.path /
# code.line.number / code.function.name on the CLIENT/PRODUCER spans your app
# issues, so NEAT fuses each runtime span onto the source file that made the
# call (docs/contracts/file-awareness.md). Absolute paths are emitted here;
# ingest anchors them against the service root. If the OpenTelemetry gems are
# not installed this file degrades to a no-op rather than breaking boot.

begin
  require 'opentelemetry/sdk'
  require 'opentelemetry/exporter/otlp'
  require 'opentelemetry/instrumentation/all'
  _neat_otel_loaded = true
rescue LoadError
  _neat_otel_loaded = false
end

if _neat_otel_loaded && ENV['NEAT_CALLSITE_DISABLED'] != '1'
  # Walk the Ruby call stack to the first application frame and stamp the stable
  # OTel source attributes on CLIENT/PRODUCER spans. SERVER spans are created
  # before the handler runs, so they stay route/service-grained, honestly.
  class NeatCallSiteSpanProcessor
    def initialize(root)
      @root = root.to_s.end_with?(File::SEPARATOR) ? root.to_s : root.to_s + File::SEPARATOR
    end

    def on_start(span, _parent_context)
      kind = span.kind
      return unless kind == OpenTelemetry::Trace::SpanKind::CLIENT ||
                    kind == OpenTelemetry::Trace::SpanKind::PRODUCER
      caller_locations(1).each do |loc|
        file = loc.absolute_path || loc.path
        next if file.nil?
        next unless file.start_with?(@root)
        next if file.include?('/vendor/') || file.include?('/.bundle/')
        next if file.end_with?('neat_otel.rb')
        span.set_attribute('code.file.path', file)
        span.set_attribute('code.line.number', loc.lineno)
        span.set_attribute('code.function.name', loc.label.to_s)
        break
      end
    rescue StandardError
      # never break the host application
    end

    def on_finish(_span); end

    def force_flush(timeout: nil)
      OpenTelemetry::SDK::Trace::Export::SUCCESS
    end

    def shutdown(timeout: nil)
      OpenTelemetry::SDK::Trace::Export::SUCCESS
    end
  end

  _neat_root = defined?(Rails) ? Rails.root.to_s : Dir.pwd
  _neat_service = ENV.fetch('OTEL_SERVICE_NAME', '${service}')
  _neat_endpoint = ENV.fetch('OTEL_EXPORTER_OTLP_TRACES_ENDPOINT', '${endpoint}')

  OpenTelemetry::SDK.configure do |c|
    c.service_name = _neat_service
    c.use_all
    c.add_span_processor(
      OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor.new(
        OpenTelemetry::Exporter::OTLP::Exporter.new(endpoint: _neat_endpoint)
      )
    )
    c.add_span_processor(NeatCallSiteSpanProcessor.new(_neat_root))
  end
end
`
}

async function exists(p: string): Promise<boolean> {
  try {
    await fs.stat(p)
    return true
  } catch {
    return false
  }
}

async function detect(serviceDir: string): Promise<boolean> {
  for (const marker of RUBY_MARKERS) {
    if (await exists(path.join(serviceDir, marker))) return true
  }
  return false
}

// A Rails app carries a `rails` gem or the conventional Rails layout. Only a
// Rails app gets the convention-loaded initializer; a plain-Ruby service still
// gets the gems but leaves boot-time wiring to the operator (there is no
// universal auto-load point outside Rails).
async function isRailsApp(serviceDir: string, gemfile: string | null): Promise<boolean> {
  if (gemfile && /^\s*gem\s+['"]rails['"]/m.test(gemfile)) return true
  for (const marker of ['config/application.rb', 'config/environment.rb', 'bin/rails']) {
    if (await exists(path.join(serviceDir, marker))) return true
  }
  return false
}

// True when the Gemfile already declares `gem '<name>'` at any version.
function gemPresent(gemfile: string, name: string): boolean {
  const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  return new RegExp(`^\\s*gem\\s+['"]${escaped}['"]`, 'm').test(gemfile)
}

async function readGemfile(serviceDir: string): Promise<{ file: string; body: string } | null> {
  const file = path.join(serviceDir, 'Gemfile')
  if (!(await exists(file))) return null
  return { file, body: await fs.readFile(file, 'utf8') }
}

async function plan(serviceDir: string, opts?: PlanOptions): Promise<InstallPlan> {
  const empty: InstallPlan = {
    language: 'ruby',
    serviceDir,
    dependencyEdits: [],
    entrypointEdits: [],
    envEdits: [],
  }

  const gemfile = await readGemfile(serviceDir)

  // Manifest edits only when a real Gemfile is on disk. A directory that carries
  // only Gemfile.lock has no manifest we may safely write, so we add nothing —
  // and never reference the lockfile.
  const dependencyEdits: DependencyEdit[] = []
  if (gemfile) {
    for (const gem of RUBY_GEMS) {
      if (!gemPresent(gemfile.body, gem.name)) {
        dependencyEdits.push({ file: gemfile.file, kind: 'add', name: gem.name, version: gem.version })
      }
    }
  }

  const rails = await isRailsApp(serviceDir, gemfile?.body ?? null)
  const initializer = path.join(serviceDir, INITIALIZER_REL)
  const generatedFiles: GeneratedFile[] = []
  if (rails && !(await exists(initializer))) {
    generatedFiles.push({
      file: initializer,
      contents: neatOtelRb({ project: opts?.project }),
      skipIfExists: true,
    })
  }

  if (dependencyEdits.length === 0 && generatedFiles.length === 0) {
    return empty
  }

  const envEdits: EnvEdit[] = [
    { file: null, key: 'OTEL_EXPORTER_OTLP_ENDPOINT', value: 'http://localhost:4318' },
  ]

  return {
    language: 'ruby',
    serviceDir,
    dependencyEdits,
    entrypointEdits: [],
    envEdits,
    ...(generatedFiles.length > 0 ? { generatedFiles } : {}),
  }
}

async function writeFileAtomic(file: string, contents: string): Promise<void> {
  const tmp = `${file}.${process.pid}.${Date.now()}.tmp`
  await fs.writeFile(tmp, contents, 'utf8')
  await fs.rename(tmp, file)
}

// Append the missing gems to the Gemfile, preserving everything already there
// (merge, never clobber). A trailing newline is kept so the file stays clean.
async function applyGemfile(file: string, edits: DependencyEdit[], original: string): Promise<void> {
  const lines = edits.filter((e) => e.kind === 'add').map((e) => `gem '${e.name}', '${e.version}'`)
  const banner = `\n# ${NEAT_OTEL_STAMP} — OpenTelemetry gems added by NEAT\n`
  const trailing = original.endsWith('\n') ? '' : '\n'
  await writeFileAtomic(file, `${original}${trailing}${banner}${lines.join('\n')}\n`)
}

async function rollback(
  serviceDir: string,
  language: string,
  originals: Map<string, string>,
  created: string[],
): Promise<void> {
  const restored: string[] = []
  for (const [file, raw] of originals.entries()) {
    try {
      await fs.writeFile(file, raw, 'utf8')
      restored.push(file)
    } catch {
      // best-effort
    }
  }
  const removed: string[] = []
  for (const file of created) {
    try {
      await fs.rm(file, { force: true })
      removed.push(file)
    } catch {
      // best-effort
    }
  }
  const body = [
    '# neat-rollback.patch',
    '',
    `# Generated after a partial apply failure in the ${language} installer.`,
    '# Files listed below were restored to their pre-apply contents.',
    '',
    ...restored.map((f) => `restored: ${f}`),
    ...removed.map((f) => `removed: ${f}`),
    '',
  ]
  await fs.writeFile(path.join(serviceDir, 'neat-rollback.patch'), body.join('\n'), 'utf8')
}

async function apply(installPlan: InstallPlan): Promise<ApplyResult> {
  const { serviceDir } = installPlan
  const generatedFiles = installPlan.generatedFiles ?? []
  const manifests = new Set(installPlan.dependencyEdits.map((e) => e.file))

  if (manifests.size === 0 && generatedFiles.length === 0) {
    return { serviceDir, outcome: 'already-instrumented', writtenFiles: [] }
  }

  const originals = new Map<string, string>()
  for (const file of manifests) {
    try {
      originals.set(file, await fs.readFile(file, 'utf8'))
    } catch {
      // Mutation fails loudly below; rollback covers what did land.
    }
  }

  const writtenFiles: string[] = []
  const created: string[] = []
  try {
    // Generated initializer first (createOnly, ADR-069 §6): an existing file is
    // preserved untouched; a new one is tracked so rollback can delete it.
    for (const gf of generatedFiles) {
      if (await exists(gf.file)) continue
      await fs.mkdir(path.dirname(gf.file), { recursive: true })
      await writeFileAtomic(gf.file, gf.contents)
      writtenFiles.push(gf.file)
      created.push(gf.file)
    }

    for (const file of manifests) {
      const raw = originals.get(file)
      if (raw === undefined) throw new Error(`ruby installer: cannot read ${file} during apply`)
      const edits = installPlan.dependencyEdits.filter((e) => e.file === file)
      if (edits.length > 0) {
        await applyGemfile(file, edits, raw)
        writtenFiles.push(file)
      }
    }
  } catch (err) {
    await rollback(serviceDir, installPlan.language, originals, created)
    throw err
  }

  // When the Gemfile changed, the operator resolves the new gems with bundler —
  // NEAT doesn't run it (it can't guarantee bundler is on PATH), it instructs
  // (ADR-186). The orchestrator surfaces this instead of spawning the JS PM.
  const wroteManifest = writtenFiles.some((f) => path.basename(f) === 'Gemfile')

  return {
    serviceDir,
    outcome: writtenFiles.length > 0 ? 'instrumented' : 'already-instrumented',
    writtenFiles,
    ...(wroteManifest ? { followUpInstall: 'bundle install' } : {}),
  }
}

export const rubyInstaller: Installer = { name: 'ruby', detect, plan, apply }
