/**
 * Generated-file templates for the Node SDK installer (ADR-069 §1).
 *
 * Three flavors so the inserted file matches the host package's module
 * system: CJS for `require`-based packages, ESM for `import`-based, TS for
 * TypeScript entries. Each variant loads the per-package `.env.neat`
 * (ADR-069 §4) before the auto-instrumentation hook attaches so
 * `OTEL_SERVICE_NAME` and the endpoint are in scope.
 */

// Header comment that ships at the top of every generated otel-init. Stable
// across flavors so a grep for the header line finds every generated file in
// a target codebase. Used by the idempotency check too (ADR-069 §6).
export const OTEL_INIT_HEADER = '// Generated by `neat init --apply` (ADR-069). OpenTelemetry auto-instrumentation hook.'

export const OTEL_INIT_CJS = `${OTEL_INIT_HEADER}
// Loads .env.neat (OTEL_SERVICE_NAME, OTEL_EXPORTER_OTLP_ENDPOINT) before
// the auto-instrumentation hook attaches. Configure via the env file.
const path = require('node:path')
try {
  require('dotenv').config({ path: path.join(__dirname, '.env.neat') })
} catch (err) {
  // dotenv unavailable — fall through to process.env.
}
require('@opentelemetry/auto-instrumentations-node/register')
`

export const OTEL_INIT_ESM = `${OTEL_INIT_HEADER}
// Loads .env.neat (OTEL_SERVICE_NAME, OTEL_EXPORTER_OTLP_ENDPOINT) before
// the auto-instrumentation hook attaches. Configure via the env file.
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import dotenv from 'dotenv'

const here = path.dirname(fileURLToPath(import.meta.url))
dotenv.config({ path: path.join(here, '.env.neat') })

await import('@opentelemetry/auto-instrumentations-node/register')
`

export const OTEL_INIT_TS = `${OTEL_INIT_HEADER}
// Loads .env.neat (OTEL_SERVICE_NAME, OTEL_EXPORTER_OTLP_ENDPOINT) before
// the auto-instrumentation hook attaches. Configure via the env file.
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import dotenv from 'dotenv'

const here = path.dirname(fileURLToPath(import.meta.url))
dotenv.config({ path: path.join(here, '.env.neat') })

await import('@opentelemetry/auto-instrumentations-node/register')
`

// .env.neat shape (ADR-069 §4). Two keys: OTEL_SERVICE_NAME (per-package,
// scope-preserved) and OTEL_EXPORTER_OTLP_ENDPOINT (uniform across packages,
// matches what the daemon exposes at :4318).
export function renderEnvNeat(serviceName: string): string {
  return [
    '# Generated by `neat init --apply` (ADR-069).',
    `OTEL_SERVICE_NAME=${serviceName}`,
    'OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318',
    '',
  ].join('\n')
}
