/**
 * Generated-file templates for the Node SDK installer (ADR-069 §1).
 *
 * Three flavors so the inserted file matches the host package's module
 * system: CJS for `require`-based packages, ESM for `import`-based, TS for
 * TypeScript entries. Env vars are inlined as `process.env.X ||=` defaults
 * rather than loaded from `.env.neat` at runtime — `__dirname` /
 * `import.meta.url` resolve unpredictably once a bundler rewrites the
 * generated file (Brief-smoke evidence, issue #369), so we let the OTel SDK
 * read its config from the same `process.env` either way. Platform env
 * (Vercel / Railway / Fly / etc.) stays authoritative at deploy time;
 * `||=` keeps the local default for laptop dev only.
 */

// Header comment that ships at the top of every generated otel-init. Stable
// across flavors so a grep for the header line finds every generated file in
// a target codebase. Used by the idempotency check too (ADR-069 §6).
export const OTEL_INIT_HEADER = '// Generated by `neat init --apply` (ADR-069). OpenTelemetry auto-instrumentation hook.'

// Version stamp on the generated otel-init (file-awareness.md §4). A NEAT-owned
// file carries OTEL_INIT_HEADER; the stamp records which template revision wrote
// it. On re-run, an existing NEAT-owned file whose stamp is older than the
// current one is regenerated (a hand-written init — no header — is never
// touched). Bump the revision whenever the generated body changes shape.
export const OTEL_INIT_STAMP =
  '// neat-template-version: 3 — file-first call-site capture (ADR-089) + OTLP bearer auth (#410).'

// OTLP exporter auth (ADR-073 §3/§4, #410). When the operator runs the
// instrumented app with `NEAT_OTEL_TOKEN` set — the same secret the daemon's
// OTLP receiver reads (`NEAT_OTEL_TOKEN ?? NEAT_AUTH_TOKEN`) — the exporter
// sends `Authorization: Bearer <token>` so a secured daemon accepts the spans.
// Unset (laptop dev against a loopback daemon with no token) sends no header,
// matching the daemon's unauthenticated loopback path. The token is the single
// source: it lives in the environment, never inlined into the generated file.
// `||=` keeps any platform-set header (Vercel / Railway / Fly) authoritative.
export const OTEL_OTLP_HEADERS_JS =
  "if (process.env.NEAT_OTEL_TOKEN) process.env.OTEL_EXPORTER_OTLP_HEADERS ||= 'Authorization=Bearer ' + process.env.NEAT_OTEL_TOKEN"

// Inlined call-site SpanProcessor (file-awareness.md §4–5). On CLIENT (2) /
// PRODUCER (3) span start it walks `new Error().stack` and sets the OTel
// `code.filepath` / `code.lineno` / `code.function` attributes to the first
// user frame — outside node_modules, @opentelemetry, node: internals, and the
// processor itself. Read synchronously at span creation, where the user's
// calling frame is still on the stack (it does not survive an await otherwise).
// Self-contained: NEAT can't import its own package into a user's generated
// file, so the logic is inlined verbatim. The same source is exercised by the
// capture spike (installers/callsite-processor.test.ts) so a regression here
// fails CI before it ships. The `ts` flag adds the few type annotations a
// strict tsconfig needs; the runtime logic is identical across flavors.
function neatCallsiteProcessorSource(ts: boolean): string {
  const stackT = ts ? ': string' : ''
  const spanT = ts ? ': any' : ''
  const strOpt = ts ? ': string | undefined' : ''
  return `function __neatPickUserFrame(stack${stackT}) {
  const lines = String(stack || '').split('\\n')
  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i].trim()
    if (raw.indexOf('at ') !== 0) continue
    if (raw.indexOf('node_modules') !== -1) continue
    if (raw.indexOf('@opentelemetry') !== -1) continue
    if (raw.indexOf('node:') !== -1) continue
    if (raw.indexOf('NeatCallSiteSpanProcessor') !== -1) continue
    const bodyText = raw.slice(3)
    const loc = bodyText.match(/:(\\d+):(\\d+)\\)?$/)
    if (!loc) continue
    const paren = bodyText.lastIndexOf('(')
    let filepath${strOpt}
    let fn${strOpt}
    if (paren !== -1) {
      fn = bodyText.slice(0, paren).trim()
      if (fn.indexOf('async ') === 0) fn = fn.slice(6)
      if (fn.indexOf('new ') === 0) fn = fn.slice(4)
      filepath = bodyText.slice(paren + 1, bodyText.length - loc[0].length)
    } else {
      filepath = bodyText.slice(0, bodyText.length - loc[0].length)
    }
    if (filepath.indexOf('file://') === 0) filepath = filepath.slice(7)
    if (!filepath) continue
    return { filepath: filepath, lineno: Number(loc[1]), function: fn || undefined }
  }
  return null
}

class NeatCallSiteSpanProcessor {
  onStart(span${spanT}) {
    if (!span || (span.kind !== 2 && span.kind !== 3)) return
    const frame = __neatPickUserFrame(new Error().stack)
    if (!frame) return
    span.setAttribute('code.filepath', frame.filepath)
    if (typeof frame.lineno === 'number') span.setAttribute('code.lineno', frame.lineno)
    if (frame.function) span.setAttribute('code.function', frame.function)
  }
  onEnd() {}
  forceFlush() { return Promise.resolve() }
  shutdown() { return Promise.resolve() }
}`
}

// The runtime processor source, exported so the capture spike can materialise
// and exercise the exact bytes that ship in the generated file.
export const CALLSITE_PROCESSOR_JS = neatCallsiteProcessorSource(false)
export const CALLSITE_PROCESSOR_TS = neatCallsiteProcessorSource(true)

// Post-`sdk.start()` registration. NodeSDK keeps its env-configured OTLP
// exporter (passing `spanProcessors` to the constructor would replace it); we
// add the call-site processor to the started provider instead, via the public
// `getDelegate()` + `addSpanProcessor()` surface. Best-effort by design: a
// provider shape we don't recognise degrades to no capture, never to no export.
function neatRegisterCallsiteSource(ts: boolean): string {
  const providerT = ts ? ': any' : ''
  return `try {
  const provider${providerT} = trace.getTracerProvider()
  const delegate = provider && typeof provider.getDelegate === 'function' ? provider.getDelegate() : provider
  if (delegate && typeof delegate.addSpanProcessor === 'function') {
    delegate.addSpanProcessor(new NeatCallSiteSpanProcessor())
  }
} catch {
  // capture is best-effort; span export is unaffected
}`
}

// __SERVICE_NAME__ → the ServiceNode id (the package's `pkg.name`, or the
// directory basename for nameless packages); __PROJECT__ → the registered
// project basename; __INSTRUMENTATION_BLOCK__ → a (possibly empty) sequence
// of `instrumentations.push(...)` lines for non-bundled instrumentations
// (Prisma for v0.4.5; more libraries via the v0.5.0 registry). All three are
// substituted at apply time via renderNodeOtelInit().
//
// v0.4.5 — explicit `NodeSDK` construction replaces the
// `auto-instrumentations-node/register` shorthand so non-bundled libraries
// (Prisma's Rust query engine bypasses node-pg; Drizzle, BetterAuth, etc.
// have their own packages) can compose into the same `instrumentations`
// array without templating a different file shape per library.
export const OTEL_INIT_CJS = `${OTEL_INIT_HEADER}
${OTEL_INIT_STAMP}
process.env.OTEL_SERVICE_NAME ||= '__SERVICE_NAME__'
process.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT ||= 'http://localhost:4318/projects/__PROJECT__/v1/traces'
${OTEL_OTLP_HEADERS_JS}

const { NodeSDK } = require('@opentelemetry/sdk-node')
const { getNodeAutoInstrumentations } = require('@opentelemetry/auto-instrumentations-node')
const { trace } = require('@opentelemetry/api')

${CALLSITE_PROCESSOR_JS}

const instrumentations = [getNodeAutoInstrumentations()]
__INSTRUMENTATION_BLOCK__
const sdk = new NodeSDK({ instrumentations })
sdk.start()
${neatRegisterCallsiteSource(false)}
`

export const OTEL_INIT_ESM = `${OTEL_INIT_HEADER}
${OTEL_INIT_STAMP}
process.env.OTEL_SERVICE_NAME ||= '__SERVICE_NAME__'
process.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT ||= 'http://localhost:4318/projects/__PROJECT__/v1/traces'
${OTEL_OTLP_HEADERS_JS}

import { NodeSDK } from '@opentelemetry/sdk-node'
import { getNodeAutoInstrumentations } from '@opentelemetry/auto-instrumentations-node'
import { trace } from '@opentelemetry/api'

${CALLSITE_PROCESSOR_JS}

const instrumentations = [getNodeAutoInstrumentations()]
__INSTRUMENTATION_BLOCK__
const sdk = new NodeSDK({ instrumentations })
sdk.start()
${neatRegisterCallsiteSource(false)}
`

export const OTEL_INIT_TS = `${OTEL_INIT_HEADER}
${OTEL_INIT_STAMP}
process.env.OTEL_SERVICE_NAME ||= '__SERVICE_NAME__'
process.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT ||= 'http://localhost:4318/projects/__PROJECT__/v1/traces'
${OTEL_OTLP_HEADERS_JS}

import { NodeSDK } from '@opentelemetry/sdk-node'
import { getNodeAutoInstrumentations } from '@opentelemetry/auto-instrumentations-node'
import { trace } from '@opentelemetry/api'

${CALLSITE_PROCESSOR_TS}

const instrumentations = [getNodeAutoInstrumentations()]
__INSTRUMENTATION_BLOCK__
const sdk = new NodeSDK({ instrumentations })
sdk.start()
${neatRegisterCallsiteSource(true)}
`

// Substitute __SERVICE_NAME__, __PROJECT__, and __INSTRUMENTATION_BLOCK__
// at apply time. The third arg is a list of registration snippets — one per
// non-bundled instrumentation the installer detected (e.g. Prisma). An empty
// list collapses the placeholder to nothing so the generated file stays
// readable on the common "auto-instrumentations covers everything" path.
export function renderNodeOtelInit(
  template: string,
  serviceName: string,
  projectName: string,
  registrations: readonly string[] = [],
): string {
  const block = registrations.length === 0 ? '' : `\n${registrations.join('\n')}\n`
  return template
    .replace(/__SERVICE_NAME__/g, serviceName)
    .replace(/__PROJECT__/g, projectName)
    .replace(/__INSTRUMENTATION_BLOCK__\n?/g, block)
}

// .env.neat shape (ADR-069 §4, amended v0.4.1 — refs #339, v0.4.4 — refs
// #367 + #369, v0.4.8 — refs #410). Two keys: OTEL_SERVICE_NAME (the
// ServiceNode id — the package's own name, scope-preserved, so spans land on
// per-service nodes inside the project's graph) and
// OTEL_EXPORTER_OTLP_TRACES_ENDPOINT (the project-scoped URL the daemon mounts
// at /projects/<project>/v1/traces). Both env vars are advisory only — the
// generated `otel-init` inlines them via `process.env.X ||=` so bundlers can't
// lose them; the file is kept so operators can grep for service.name → project
// mapping in one place. A commented `NEAT_OTEL_TOKEN` hint documents the single
// source of the OTLP bearer (#410): set it to the secret the daemon's receiver
// expects and the generated init sends `Authorization: Bearer <token>`.
export function renderEnvNeat(serviceName: string, projectName: string): string {
  return [
    '# Generated by `neat init --apply` (ADR-069).',
    `OTEL_SERVICE_NAME=${serviceName}`,
    `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4318/projects/${projectName}/v1/traces`,
    '# Set NEAT_OTEL_TOKEN to the daemon\'s OTLP secret to authenticate exported spans (#410).',
    '# NEAT_OTEL_TOKEN=',
    '',
  ].join('\n')
}

// ── Next.js framework-aware templates (ADR-073 §1, ADR-069 §3). ─────────
//
// Next.js owns its own boot — `pkg.main` is unused, and the auto-instrumentation
// register hook can't run before user code. Next 13+ ships an `instrumentation`
// file at the project root with an async `register()` export the framework
// invokes during server start (Node runtime only). For Edge / browser runtimes
// the file is ignored.
//
// Two-file shape: `instrumentation.{ts,js}` keeps the runtime gate so the
// Node SDK doesn't load on the Edge runtime; `instrumentation.node.{ts,js}`
// carries the SDK init itself. Both files sit at the project root.

export const NEXT_INSTRUMENTATION_HEADER =
  '// Generated by `neat init --apply` (ADR-073). Next.js instrumentation hook.'

export const NEXT_INSTRUMENTATION_TS = `${NEXT_INSTRUMENTATION_HEADER}
export async function register() {
  if (process.env.NEXT_RUNTIME === 'nodejs') {
    await import('./instrumentation.node')
  }
}
`

export const NEXT_INSTRUMENTATION_JS = `${NEXT_INSTRUMENTATION_HEADER}
export async function register() {
  if (process.env.NEXT_RUNTIME === 'nodejs') {
    await import('./instrumentation.node')
  }
}
`

// Env vars are inlined as process.env defaults so they survive Turbopack /
// Webpack bundling — `import.meta.url` resolves to a path under .next/dev/
// server/chunks/ once Next compiles this file, which would miss .env.neat.
// `process.env.X ||=` keeps platform env (Vercel / Railway / Fly / etc.)
// authoritative at deploy time while the local default carries the routing
// key the daemon needs to map spans back to this project. The endpoint uses
// the project-scoped URL form so the daemon never has to guess which project
// owns the span (issue #367); the OTel SDK reads the env vars from
// process.env directly, so no file-system lookup is required at runtime.
export const NEXT_INSTRUMENTATION_NODE_TS = `${NEXT_INSTRUMENTATION_HEADER}
process.env.OTEL_SERVICE_NAME ||= '__SERVICE_NAME__'
process.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT ||= 'http://localhost:4318/projects/__PROJECT__/v1/traces'
${OTEL_OTLP_HEADERS_JS}

import { NodeSDK } from '@opentelemetry/sdk-node'
import { getNodeAutoInstrumentations } from '@opentelemetry/auto-instrumentations-node'

const instrumentations = [getNodeAutoInstrumentations()]
__INSTRUMENTATION_BLOCK__
new NodeSDK({ instrumentations }).start()
`

export const NEXT_INSTRUMENTATION_NODE_JS = `${NEXT_INSTRUMENTATION_HEADER}
process.env.OTEL_SERVICE_NAME ||= '__SERVICE_NAME__'
process.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT ||= 'http://localhost:4318/projects/__PROJECT__/v1/traces'
${OTEL_OTLP_HEADERS_JS}

const { NodeSDK } = require('@opentelemetry/sdk-node')
const { getNodeAutoInstrumentations } = require('@opentelemetry/auto-instrumentations-node')

const instrumentations = [getNodeAutoInstrumentations()]
__INSTRUMENTATION_BLOCK__
new NodeSDK({ instrumentations }).start()
`

// Substitute the placeholders at apply time so the generated file carries the
// ServiceNode id (`__SERVICE_NAME__`) and the registered project name
// (`__PROJECT__`) verbatim. The two roles diverged in v0.4.4: the service name
// names the ServiceNode inside one project's graph, the project basename is
// the URL routing key. v0.4.5 adds __INSTRUMENTATION_BLOCK__ — a (possibly
// empty) sequence of `instrumentations.push(...)` calls for non-bundled
// libraries like Prisma whose query engines bypass the auto-instrumentation
// set's coverage.
export function renderNextInstrumentationNode(
  template: string,
  serviceName: string,
  projectName: string,
  registrations: readonly string[] = [],
): string {
  const block = registrations.length === 0 ? '' : `\n${registrations.join('\n')}\n`
  return template
    .replace(/__SERVICE_NAME__/g, serviceName)
    .replace(/__PROJECT__/g, projectName)
    .replace(/__INSTRUMENTATION_BLOCK__\n?/g, block)
}

// ── Meta-framework templates (ADR-074 §3). ──────────────────────────────
//
// Remix, SvelteKit, Nuxt, and Astro each own their boot path. The installer
// emits one OTel-init module that loads `.env.neat` and starts the Node SDK,
// then either creates or injects an import into the framework's canonical
// hook file. Templates mirror the Next.js pair in shape — one generated init
// module, one optional framework-hook stub for the absent-file case.

export const FRAMEWORK_OTEL_INIT_HEADER =
  '// Generated by `neat init --apply` (ADR-074). OpenTelemetry SDK hook.'

// Same inline-defaults pattern as the plain-Node + Next templates: env vars
// arrive on `process.env` via the apply-time substitution below so bundler
// path mangling (issue #369) can't lose them. `__SERVICE_NAME__` /
// `__PROJECT__` are substituted via renderFrameworkOtelInit().
const FRAMEWORK_OTEL_INIT_TS_BODY = `${FRAMEWORK_OTEL_INIT_HEADER}
process.env.OTEL_SERVICE_NAME ||= '__SERVICE_NAME__'
process.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT ||= 'http://localhost:4318/projects/__PROJECT__/v1/traces'
${OTEL_OTLP_HEADERS_JS}

import { NodeSDK } from '@opentelemetry/sdk-node'
import { getNodeAutoInstrumentations } from '@opentelemetry/auto-instrumentations-node'

const sdk = new NodeSDK({
  serviceName: process.env.OTEL_SERVICE_NAME,
  instrumentations: [getNodeAutoInstrumentations()],
})
sdk.start()
`

const FRAMEWORK_OTEL_INIT_JS_BODY = `${FRAMEWORK_OTEL_INIT_HEADER}
process.env.OTEL_SERVICE_NAME ||= '__SERVICE_NAME__'
process.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT ||= 'http://localhost:4318/projects/__PROJECT__/v1/traces'
${OTEL_OTLP_HEADERS_JS}

const { NodeSDK } = require('@opentelemetry/sdk-node')
const { getNodeAutoInstrumentations } = require('@opentelemetry/auto-instrumentations-node')

const sdk = new NodeSDK({
  serviceName: process.env.OTEL_SERVICE_NAME,
  instrumentations: [getNodeAutoInstrumentations()],
})
sdk.start()
`

export function renderFrameworkOtelInit(
  template: string,
  serviceName: string,
  projectName: string,
): string {
  return template
    .replace(/__SERVICE_NAME__/g, serviceName)
    .replace(/__PROJECT__/g, projectName)
}

// Remix — `app/otel.server.{ts,js}` carries the SDK bootstrap. The framework
// loads `entry.server.*` at server-process start, and a top-of-module import
// of `./otel.server` runs the bootstrap before any request handler imports.
export const REMIX_OTEL_SERVER_TS = FRAMEWORK_OTEL_INIT_TS_BODY
export const REMIX_OTEL_SERVER_JS = FRAMEWORK_OTEL_INIT_JS_BODY

// SvelteKit — `src/otel-init.{ts,js}` carries the SDK bootstrap; the
// framework's `src/hooks.server.{ts,js}` imports it. When hooks.server is
// absent, the installer writes the stub below alongside the import.
export const SVELTEKIT_OTEL_INIT_TS = FRAMEWORK_OTEL_INIT_TS_BODY
export const SVELTEKIT_OTEL_INIT_JS = FRAMEWORK_OTEL_INIT_JS_BODY

export const SVELTEKIT_HOOKS_SERVER_TS = `${FRAMEWORK_OTEL_INIT_HEADER}
import './otel-init'

import type { Handle } from '@sveltejs/kit'

export const handle: Handle = async ({ event, resolve }) => {
  return resolve(event)
}
`

export const SVELTEKIT_HOOKS_SERVER_JS = `${FRAMEWORK_OTEL_INIT_HEADER}
import './otel-init'

/** @type {import('@sveltejs/kit').Handle} */
export const handle = async ({ event, resolve }) => {
  return resolve(event)
}
`

// Nuxt — `server/plugins/otel.{ts,js}` is the convention-loaded plugin file;
// it imports the sibling `otel-init.{ts,js}` which carries the SDK bootstrap.
export const NUXT_OTEL_INIT_TS = FRAMEWORK_OTEL_INIT_TS_BODY
export const NUXT_OTEL_INIT_JS = FRAMEWORK_OTEL_INIT_JS_BODY

export const NUXT_OTEL_PLUGIN_TS = `${FRAMEWORK_OTEL_INIT_HEADER}
import './otel-init'

export default defineNitroPlugin(() => {
  // OTel SDK is initialised at module-load via the side-effect import above.
})
`

export const NUXT_OTEL_PLUGIN_JS = `${FRAMEWORK_OTEL_INIT_HEADER}
require('./otel-init')

module.exports = defineNitroPlugin(() => {
  // OTel SDK is initialised at module-load via the side-effect import above.
})
`

// Astro — `src/middleware.{ts,js}` runs once at module-load (and then per
// request via onRequest). The top-of-module import of `./otel-init` boots
// the SDK before the first request lands.
export const ASTRO_OTEL_INIT_TS = FRAMEWORK_OTEL_INIT_TS_BODY
export const ASTRO_OTEL_INIT_JS = FRAMEWORK_OTEL_INIT_JS_BODY

export const ASTRO_MIDDLEWARE_TS = `${FRAMEWORK_OTEL_INIT_HEADER}
import './otel-init'

import { defineMiddleware } from 'astro:middleware'

export const onRequest = defineMiddleware(async (context, next) => {
  return next()
})
`

export const ASTRO_MIDDLEWARE_JS = `${FRAMEWORK_OTEL_INIT_HEADER}
import './otel-init'

import { defineMiddleware } from 'astro:middleware'

export const onRequest = defineMiddleware(async (context, next) => {
  return next()
})
`
