import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { promises as fs } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import Parser from 'tree-sitter'
import Python from 'tree-sitter-python'
import { pythonInstaller } from '../src/installers/index.js'
import { neatOtelPy, injectNeatImport } from '../src/installers/python.js'

// ADR-151 rung 1b — the Python call-site span processor that gives Python
// file-grain OBSERVED. The generated neat_otel.py stamps code.file.path /
// code.line.number / code.function.name (the stable names ingest reads) on
// CLIENT/PRODUCER spans; the installer writes it and injects its import.

function hasErrorNode(node: Parser.SyntaxNode): boolean {
  if (node.type === 'ERROR' || node.isMissing) return true
  for (let i = 0; i < node.namedChildCount; i++) {
    const c = node.namedChild(i)
    if (c && hasErrorNode(c)) return true
  }
  return false
}

describe('generated neat_otel.py', () => {
  it('is syntactically valid Python', () => {
    const parser = new Parser()
    parser.setLanguage(Python)
    const tree = parser.parse(neatOtelPy())
    expect(hasErrorNode(tree.rootNode)).toBe(false)
  })

  it('emits the stable OTel code attribute names and degrades without OpenTelemetry', () => {
    const src = neatOtelPy()
    expect(src).toContain('code.file.path')
    expect(src).toContain('code.line.number')
    expect(src).toContain('code.function.name')
    // ADR-144 discipline: a bare app without OTel installed must not crash.
    expect(src).toContain('_NEAT_OTEL = False')
    // Never break the host app.
    expect(src).toContain('# never break the host application')
  })

  it('writes the generated bytes out for the live capture check', async () => {
    const out = process.env.NEAT_GENERATED_OTEL_PATH
    if (out) await fs.writeFile(out, neatOtelPy(), 'utf8')
    expect(neatOtelPy().length).toBeGreaterThan(0)
  })
})

describe('injectNeatImport', () => {
  it('inserts the import at the top of a plain module', () => {
    const out = injectNeatImport('from fastapi import FastAPI\napp = FastAPI()\n')
    expect(out).not.toBeNull()
    expect(out!.split('\n')[0]).toContain('import neat_otel')
  })

  it('is idempotent — a second pass is a no-op', () => {
    const once = injectNeatImport('x = 1\n')!
    expect(injectNeatImport(once)).toBeNull()
  })

  it('keeps `from __future__` imports first (avoids a SyntaxError)', () => {
    const src = 'from __future__ import annotations\nimport os\n'
    const out = injectNeatImport(src)!
    expect(out.split('\n')[0]).toBe('from __future__ import annotations')
    expect(out).toContain('import neat_otel')
    // The neat import lands after the __future__ line.
    const lines = out.split('\n')
    expect(lines.findIndex((l) => l.includes('neat_otel'))).toBeGreaterThan(
      lines.findIndex((l) => l.includes('__future__')),
    )
  })

  it('preserves a shebang on line 0', () => {
    const out = injectNeatImport('#!/usr/bin/env python\nimport os\n')!
    expect(out.split('\n')[0]).toBe('#!/usr/bin/env python')
    expect(out.split('\n')[1]).toContain('import neat_otel')
  })
})

describe('python installer apply — generates + injects the call-site processor', () => {
  let dir: string
  beforeEach(async () => {
    dir = await fs.mkdtemp(path.join(os.tmpdir(), 'neat-py-callsite-'))
  })
  afterEach(async () => {
    await fs.rm(dir, { recursive: true, force: true })
  })

  it('writes neat_otel.py and injects the import into the resolved entry point', async () => {
    await fs.writeFile(path.join(dir, 'requirements.txt'), 'fastapi\n', 'utf8')
    await fs.writeFile(path.join(dir, 'Procfile'), 'web: uvicorn app:app --port 8000\n', 'utf8')
    await fs.writeFile(path.join(dir, 'app.py'), 'from fastapi import FastAPI\napp = FastAPI()\n', 'utf8')

    const plan = await pythonInstaller.plan(dir)
    expect(plan.entryFile).toBe(path.join(dir, 'app.py'))
    expect(plan.generatedFiles?.some((g) => path.basename(g.file) === 'neat_otel.py')).toBe(true)

    const result = await pythonInstaller.apply(plan)
    expect(result.outcome).toBe('instrumented')

    const otel = await fs.readFile(path.join(dir, 'neat_otel.py'), 'utf8')
    expect(otel).toContain('NeatCallSiteSpanProcessor')
    const app = await fs.readFile(path.join(dir, 'app.py'), 'utf8')
    expect(app.split('\n')[0]).toContain('import neat_otel')

    // Idempotent: a second apply neither re-injects nor rewrites the identical file.
    const plan2 = await pythonInstaller.plan(dir)
    const result2 = await pythonInstaller.apply(plan2)
    expect(result2.outcome).toBe('already-instrumented')
    const appAfter = await fs.readFile(path.join(dir, 'app.py'), 'utf8')
    expect(appAfter.match(/import neat_otel/g)?.length).toBe(1)
  })

  it('resolves main.py by convention when the Procfile runs it', async () => {
    await fs.writeFile(path.join(dir, 'requirements.txt'), 'flask\n', 'utf8')
    await fs.writeFile(path.join(dir, 'main.py'), 'print("hi")\n', 'utf8')
    const plan = await pythonInstaller.plan(dir)
    expect(plan.entryFile).toBe(path.join(dir, 'main.py'))
  })
})
